### ISSUE TITLE
About an errror during training process

### ISSUE THREAD

**Issue by huangqueji** [AvivNavon/nash-mtl#15]
Hi, there. When I train the model, sometimes the code will call an error which is "ValueError: Parameter value must be real". It occurs at the call path from [self.get_weighted_loss] to [self.solve_optimization(GTG.cpu().detach().numpy())] to [self.G_param.value = gtg] to [self._value = self._validate_value(val)].    

Could you help me to deal with the error? Thanks a lot!

```
Traceback (most recent call last):
  File "xxx.py", line 435, in <module>
    main()
  File "xxx.py", line 427, in main
    trainer.training(epoch)
  File "xxx.py", line 158, in training
    loss1, extra_outputs = self.weight_method.backward(
  File "methods\weight_methods.py", line 810, in backward
    return self.method.backward(losses, **kwargs)
  File "methods\weight_methods.py", line 263, in backward
    loss, extra_outputs = self.get_weighted_loss(
  File "methods\weight_methods.py", line 237, in get_weighted_loss
    alpha = self.solve_optimization(GTG.cpu().detach().numpy())
  File "methods\weight_methods.py", line 134, in solve_optimization
    self.G_param.value = gtg
  File "C:\Users\xxx\.conda\envs\xxx\lib\site-packages\cvxpy\expressions\constants\parameter.py", line 87, in value
    self._value = self._validate_value(val)
  File "C:\Users\xxx\.conda\envs\xxx\lib\site-packages\cvxpy\expressions\leaf.py", line 442, in _validate_value
    raise ValueError(
ValueError: Parameter value must be real.

Process finished with exit code 1
```

**Comment by AvivNavon** [comment]
You may have NaN, inf, etc., in your gradients. Could you please log/print the gradient to see if this is the case?

**Comment by huangqueji** [comment]
Yes, I print its gradients which have part of nan values.

**Comment by AvivSham** [comment]
This is the source of your problem. I'm closing this issue, but if another issue raises reopen it.
